callbacks:
  list:
  - earlystop
  metrics:
  - val_loss
  - val_roc
  - train_loss
  mode: max
  monitor: val_roc
  patience: 10
  write_grads: false
data:
  T_max: 1000.0
  T_min_warn: 30
  T_warning: 10.024
  augment_during_training: false
  augmentation_mode: none
  bleed_in: 0
  bleed_in_remove_from_test: true
  current_end_thresh: 10000
  current_index: 0
  current_thresh: 750000
  cut_shot_ends: false
  dt: 0.001
  equalize_classes: false
  floatx: float32
  normalizer: var
  plotting: false
  positive_example_penalty: 4.0
  recompute: false
  recompute_normalization: false
  signal_to_augment: None
  use_shots: 200000
  window_decay: 2
  window_size: 10
env:
  name: pplori
  type: anaconda3
fs_path: /tigress
model:
  PCS: true
  PCS_single_time_step: true
  backend: tensorflow
  clipnorm: 10.0
  dense_regularization: 0.01
  dense_size: 20
  dropout_prob: 0.1
  extra_dense_input: False # 2 # false
  ignore_timesteps: 100
  keras_tcn: false
  kernel_size_spatial: 7
  kernel_size_temporal: 8
  length: 1 #200
  loss_scale_factor: 1.0
  lr: 1.745790965846188e-05
  lr_decay: 0.985
  num_conv_filters: 5
  num_conv_layers: 1
  optimizer: adam
  pool_size: 2
  pred_batch_size: 1 #128
  pred_length: 1 #200
  regularization: 0.0
  return_sequences: false # true
  rnn_layers: 1
  rnn_size: 128 #200
  rnn_type: LSTM
  shallow: false
  shallow_model:
    C: 1.0
    kernel: rbf
    learning_rate: 0.1
    max_depth: 3
    n_estimators: 100
    num_samples: 1000000
    scale_pos_weight: 10.0
    skip_train: false
    type: xgboost
  simple_conv: true
  size_conv_filters: 3
  skip: 1
  stateful: true
  tcn_activation: linear
  tcn_batch_norm: false
  tcn_dropout: 0.1
  tcn_hidden: 60
  tcn_layers: 9
  tcn_nbstacks: 2
  tcn_pack_layers: 1
  tcn_skip_connect: true
  torch: false
  use_batch_norm: false
  warmup_steps: 0
num_gpus: 4
paths:
  data: d3d_data_real_time_0D
  executable: mpi_learn.py
  shallow_executable: learn.py
  shot_list_dir: /shot_lists/
  signal_prepath:
  - /../FRNN/signal_data_ipsip/
  - /../FRNN/signal_data_new_nov2019/
  - /../FRNN/signal_data_new_REAL_TIME/
  - /signal_data/
  specific_signals: []

  tensorboard_save_path: /Graph/
target: ttd
training:
  as_array_of_shots: true
  batch_generator_warmup_steps: 0
  batch_size: 1 # 256 #512 # 128
  data_parallel: false
  hyperparam_tuning: true
  max_patch_length: 100000
  num_batches_minimum: 200
  num_epochs: 1000
  num_shots_at_once: 200
  ranking_difficulty_fac: 1.0
  shuffle_training: true
  train_frac: 0.75
  use_mock_data: false
  validation_frac: 0.33
